TASK1

In [11]:
# Battery sensor data
battery_data = [
    (0, 32, 400, 20, 95),
    (1, 35, 395, 22, 88),
    (2, 38, 390, 25, 80),
    (3, 40, 385, 28, 70),
    (4, 42, 380, 30, 60),
    (5, 45, 375, 32, 48)
]

# 1. Display sensor readings
print("Battery Sensor Readings:")

for data in battery_data:
    print(data)

# 2. Identify high temperature
print("\nTemperature Status:")

for data in battery_data:
    time, temperature, voltage, current, charge = data

    if temperature > 40:
        print(f"Time {time} h: High Temperature Alert")
    else:
        print(f"Time {time} h: Temperature Normal")

# 3. Identify low battery
print("\nBattery Charge Status:")

for data in battery_data:
    time, temperature, voltage, current, charge = data

    if charge < 50:
        print(f"Time {time} h: Low Battery Alert")
    else:
        print(f"Time {time} h: Battery Charge Normal")

# 4. Battery status function
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"

print("\nBattery Status:")

for data in battery_data:
    time, temperature, voltage, current, charge = data
    print(f"Time {time} h: {battery_status(charge)}")

Battery Sensor Readings:
(0, 32, 400, 20, 95)
(1, 35, 395, 22, 88)
(2, 38, 390, 25, 80)
(3, 40, 385, 28, 70)
(4, 42, 380, 30, 60)
(5, 45, 375, 32, 48)

Temperature Status:
Time 0 h: Temperature Normal
Time 1 h: Temperature Normal
Time 2 h: Temperature Normal
Time 3 h: Temperature Normal
Time 4 h: High Temperature Alert
Time 5 h: High Temperature Alert

Battery Charge Status:
Time 0 h: Battery Charge Normal
Time 1 h: Battery Charge Normal
Time 2 h: Battery Charge Normal
Time 3 h: Battery Charge Normal
Time 4 h: Battery Charge Normal
Time 5 h: Low Battery Alert

Battery Status:
Time 0 h: High
Time 1 h: High
Time 2 h: High
Time 3 h: Medium
Time 4 h: Medium
Time 5 h: Low


TASK2


In [3]:
import numpy as np

D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

# 1. Shape
print("Shape:", D.shape)

# 2. Average of each parameter
average = np.mean(D, axis=0)

print("Average Temperature:", average[0])
print("Average Voltage:", average[1])
print("Average Current:", average[2])
print("Average Charge:", average[3])

# 3. Maximum and minimum temperature
print("Maximum Temperature:", np.max(D[:, 0]))
print("Minimum Temperature:", np.min(D[:, 0]))

# 4. Extract voltage column
voltage = D[:, 1]
print("Voltage Column:")
print(voltage)

# 5. High-temperature readings
high_temp = D[D[:, 0] > 40]
print("High Temperature Readings:")
print(high_temp)

# 6. Low-battery readings
low_battery = D[D[:, 3] < 50]
print("Low Battery Readings:")
print(low_battery)

Shape: (6, 4)
Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5
Maximum Temperature: 45
Minimum Temperature: 32
Voltage Column:
[400 395 390 385 380 375]
High Temperature Readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]
Low Battery Readings:
[[ 45 375  32  48]]


TASK3

In [4]:
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([40, 25])

Y = A @ X

print("Y =", Y)

Y = [105 115]


In [5]:
print("Transpose:")
print(A.T)

Transpose:
[[2 1]
 [1 3]]


In [6]:
print("Determinant:", np.linalg.det(A))

Determinant: 5.000000000000001


In [7]:
print("Inverse:")
print(np.linalg.inv(A))

Inverse:
[[ 0.6 -0.2]
 [-0.2  0.4]]


In [8]:
A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([100, 120])

solution = np.linalg.solve(A, B)

print("x =", solution[0])
print("y =", solution[1])

x = 36.0
y = 28.0


TASK4

In [9]:
import sympy as sp

t = sp.symbols('t')

C = 100 - 2*t - sp.Rational(1, 2)*t**2

dC_dt = sp.diff(C, t)

print("C(t) =", C)
print("dC/dt =", dC_dt)

C(t) = -t**2/2 - 2*t + 100
dC/dt = -t - 2


In [10]:
rate_t2 = dC_dt.subs(t, 2)
rate_t5 = dC_dt.subs(t, 5)

print("Rate at t=2:", rate_t2)
print("Rate at t=5:", rate_t5)

Rate at t=2: -4
Rate at t=5: -7


6. Final Decision
REJECT
	​

Reason

The battery shows several concerning operating conditions:

Temperature reaches 42°C at 4 hours and 45°C at 5 hours.
Temperature exceeds the specified 40°C alert threshold.
Battery charge falls from 95% to 48%, a 47% reduction.
The battery reaches the Low charge category at 5 hours.
The calculated discharge rate becomes more negative, changing from −4%/hour at 2 h to −7%/hour at 5 h.
Current increases from 20 A to 32 A while voltage decreases from 400 V to 375 V.

These combined trends indicate that the battery is experiencing increasing thermal and discharge stress.